### ISSUE TITLE
Part search directory

### ISSUE THREAD

**Issue by billthefish** [LasseD/buildinginstructions.js#20]
After playing around with your renderer for a bit, I like it better than brigl. I'd like to use it on the official LDraw.org site for both part previews and OMR renders. However, having to lump all the parts into one directory is a issue. Rather than have 2 parallel libraries at ldraw.org, I'd like to have the ability to search multiple directories in a specified order (e.g. unoff/p, off/p, unoff/parts, off/parts). This way I don't have to maintain a special combined directory through renames/submissions of unofficial parts and official part releases.

**Comment by billthefish** [comment]
Looking at the source, it appears as if this functionality might already there but I'm unsure on how to implement it. I noticed that I can provide my own idToUrl in the options but that's a far as I get.

**Comment by LasseD** [comment]
Hi billthefish,

I will gladly help out with this. After all, one of the purposes of this whole library is to bring something back to the LDraw community.

The existing setup (where parts and primitives are in the same folder) is made to prevent getting 404's when fetching part files. 'idToUrl' will unfortunately not be able to determine the correct folders - this will require another part of the code is changed. I will look into how the THREE.DefaultLoadingManager might be usable, or if there is an alternate which is more suitable for this use case.

**Comment by billthefish** [comment]
I did a little more poking around. It looks like you can pass a custom onError to Defaultloader. From there you might be able to have it try again with another path if the initial url doesn't work.

**Comment by LasseD** [comment]
It seems like we have arrived at the same conclusion. LoadingManager takes it as the third argument: https://github.com/mrdoob/three.js/blob/master/src/loaders/LoadingManager.js

My plan is to extend 'idToUrl' to return an array of possible locations and use onError internally to retry the various locations. 

A standard LDraw file structure with the folders 'off' and 'unoff' can then be searched by using an idToUrl function like:

idToUrl(id) {
  if(id.startsWith('48/') || id.startsWith('8/'))
    return ['off/p/' + id, 'unoff/p/' + id];
  else if(id.startWith('s/')
    return ['off/parts/' + id, 'unoff/parts/' + id];
  else
    return ['off/parts' + id, 'off/p' + id, 'unoff/parts' + id, 'unoff/p' + id];
}

**Comment by billthefish** [comment]
That's great but I think I would be useful for other users to maintain the "all in one" option. My JavaScript is rusty, would this still allow for that?

**Comment by LasseD** [comment]
Please see the latest commit to master. It has the new sample file 'sample_part_standard.htm' where files are discovered on the file system. I have also added comments in the sample file to make it easy to fit to your own file structure.

Does this work for you?

**Comment by billthefish** [comment]
Looks good. I’ll pull the update down to our server and try it out.

**Comment by billthefish** [comment]
Works great. Thanks for your help.
