### ISSUE TITLE
Warning thrown for the !CMDLINE meta

### ISSUE THREAD

**Issue by billthefish** [LasseD/buildinginstructions.js#21]
!CMDLINE is a "do nothing" meta  (at least in the context of bi.js) but it is valid LDraw command. This meta should be silently ignored (i.e. treated like a comment). 

This silent ignore should probably be extended to all other metas that aren't used by bi.js

**Comment by LasseD** [comment]
I agree. I have added it to the list on "known commands" and it has no effect other than showing a default color, such as on https://brickhub.org/p/973pa1

Does this work for you?
