### ISSUE TITLE
Failed to setup locally

### ISSUE THREAD

**Issue by urllib2** [LasseD/buildinginstructions.js#28]
Hi, I tried to host the code locally with xampp server.
I followed the instructions and I manage to work all the pages except this one: sample_instructions.htm 
In the attached img, this is what I see in my browser (chrome)
Is there any tip to make it functional.
Thanks
![sample](https://user-images.githubusercontent.com/46229376/72241260-a9752b80-35e6-11ea-9d94-4837a8d32b7f.png)

**Comment by LasseD** [comment]
Hi urllib2,
Thanks for making me aware of this. I have fixed the issue (it also affected sample_functions.htm, and sample_partslist.htm).

Can you confirm that it works on your side?

Best regards
/ Lasse

**Comment by urllib2** [comment]
Yes, it works now!
Thank you for this great contribution to the community
Regards
