### ISSUE TITLE
Issue with the modification of css

### ISSUE THREAD

**Issue by urllib2** [LasseD/buildinginstructions.js#30]
Hi, I want to do some customization to the CSS. I searched for the css files but I couldn't figure out which one should I edit in order to change the layout and colors of the sample_instructions.htm page.
Could you indicate the files to modify in order to change the appearance of the sample_instructions.htm.
Thanks

**Comment by LasseD** [comment]
In general you can find the referenced CSS files in the headers of the HTML documents.

For the HTML document "sample_instructions.htm", the header contains:

`<link href="css/instructions.css" rel="stylesheet" type="text/css" />
    <link href="css/preview.css" rel="stylesheet" type="text/css">
    <link href="css/buttons.css" rel="stylesheet" type="text/css" />
    <link href="css/options.css" rel="stylesheet" type="text/css" />`

So the CSS files are: "css/instructions.css", "css/preview.css", "css/buttons.css" and "css/options.css".

**Comment by urllib2** [comment]
Thank you! I will try to play with these files.
