### ISSUE TITLE
Model fails to load when starting with a submodel

### ISSUE THREAD

**Issue by mfeldt** [LasseD/buildinginstructions.js#31]
**Describe the bug**
I have a complex model consisiting of sub-models only, which fails to load.
The error is "Empty first step!"

**To Reproduce**
Since the model is complex, I tried to produce a kind of minimal example, attached at the bottom. This produces a different error (empty ID), but it also starts with a submodel, so I presume that once this works, the next one will be simple...

**Expected behavior**
I'd expect to see some stepped instructions, as e.g. in lpub3d

**Screenshots**

**Device (please complete the following information):**
 - Device/OS:Linux+Windows
 - Browser firefox
 - Version head

**Additional context**
Try this model:
===========================================================
```
0 FILE pyramid2_rev.lxf
0 Name: pyramid2_rev.lxf
0 Author: Undefined
1 16 7.405296803 -71.99983215 219.8517609 1 0 0 0 1 0 0 0 1 pyramid2_rev.lxf_0
0 STEP
1 4 79.9999923706 0.0000724792 -80 1 0 0 0 1 0 0 0 1 3001.dat
1 4 -0.0000038147 0.0000724792 -80 1 0 0 0 1 0 0 0 1 3001.dat
1 4 -80.0000152588 0.0000724792 -80 1 0 0 0 1 0 0 0 1 3001.dat
1 4 -100 0.0000724792 -20 0 0 -1 0 1 0 1 0 0 3001.dat
1 4 100 0.0000972748 -20 0 0 -1 0 1 0 1 0 0 3001.dat
1 4 -100.0000305176 0.000120163 60 0 0 -1 0 1 0 1 0 0 3001.dat
1 4 100 0.000120163 60 0 0 -1 0 1 0 1 0 0 3001.dat
1 4 80 0.000120163 120.0000152588 -1 0 0 0 1 0 0 0 -1 3001.dat
1 4 0 0.0001678467 120.0000152588 -1 0 0 0 1 0 0 0 -1 3001.dat
1 4 -80.0000152588 0.0001449585 120.0000305176 -1 0 0 0 1 0 0 0 -1 3001.dat
0 STEP
1 1 59.9999847412 -24 -59.9999923706 1 0 0 0 1 0 0 0 1 3001.dat
1 1 -20.0000095367 -24 -59.9999923706 1 0 0 0 1 0 0 0 1 3001.dat
1 1 -79.9999923706 -24 -39.9999923706 0 0 -1 0 1 0 1 0 0 3001.dat
1 1 -79.9999923706 -24 40.0000228882 0 0 -1 0 1 0 1 0 0 3001.dat
1 1 -59.9999923706 -24 100.0000228882 1 0 0 0 1 0 0 0 1 3001.dat
1 1 19.9999980927 -24 100.0000076294 1 0 0 0 1 0 0 0 1 3001.dat
1 1 80 -24 80.0000076294 0 0 1 0 1 0 -1 0 0 3001.dat
1 1 79.9999923706 -24 0.0000076294 0 0 1 0 1 0 -1 0 0 3001.dat
0 STEP
1 16 10.00000858 -23.99987221 70.00000763 1 0 0 0 1 0 0 0 1 pyramid2_rev.lxf_3
0 STEP
1 15 -19.9999866486 -71.9998703003 60.0000076294 1 0 0 0 1 0 0 0 1 3001.dat
1 15 19.9999732971 -71.9998931885 -19.9999771118 1 0 0 0 1 0 0 0 1 3001.dat
1 15 -40.0000076294 -71.9999160767 -0.0000038147 0 0 -1 0 1 0 1 0 0 3001.dat
1 15 39.9999885559 -71.9998931885 40.0000152588 0 0 -1 0 1 0 1 0 0 3001.dat
0 STEP
1 16 -30.00000763 -71.99989319 30.0000248 1 0 0 0 1 0 0 0 1 pyramid2_rev.lxf_5
0 STEP
0 !LPUB INSERT MODEL
0 !LPUB INSERT PAGE
0 STEP
0 NOFILE 
0 FILE pyramid2_rev.lxf_0
0 Name: pyramid2_rev.lxf_0
0 Author: Undefined
1 2 -17.4052696228 -24 -9.8517303467 -0.8702634573 0 0.4925865233 0 1 0 -0.4925865233 0 -0.8702634573 3622.dat
1 15 -17.4053058624 0.0000014901 -9.851776123 -0.9182773829 0 -0.3959376216 0 1 0 0.3959376216 0 -0.9182773829 3622.dat
1 14 -17.4053134918 24 -9.8517436981 -0.229424268 0 -0.9733265042 0 1 0 0.9733265042 0 -0.229424268 3622.dat
1 1 -17.4053020477 47.9998283386 -9.8517198563 0.6290366054 0 -0.7773756385 0 1 0 0.7773756385 0 0.6290366054 3622.dat
1 4 -17.4053039551 72 -9.8517570496 0.9992797375 0 0.0379474312 0 1 0 -0.0379474312 0 0.9992797375 3622.dat
0 STEP
0 NOFILE 
0 FILE pyramid2_rev.lxf_3_1_1
0 Name: pyramid2_rev.lxf_3_1_1
0 Author: Undefined
1 70 10 -24 10 1 0 0 0 1 0 0 0 1 3003.dat
1 70 9.9999961853 0.0000014901 -10.0000047684 1 0 0 0 1 0 0 0 1 3001.dat
1 70 9.9999961853 0.0000014901 30.0000095367 1 0 0 0 1 0 0 0 1 3001.dat
1 70 10 24.0000019073 10 1 0 0 0 1 0 0 0 1 3003.dat
0 STEP
0 NOFILE 
0 FILE pyramid2_rev.lxf_3_1
0 Name: pyramid2_rev.lxf_3_1
0 Author: Undefined
1 70 10 -24 10 1 0 0 0 1 0 0 0 1 3003.dat
1 70 10 0.0000014901 10 1 0 0 0 1 0 0 0 1 3003.dat
1 70 10 24.0000019073 10 1 0 0 0 1 0 0 0 1 3003.dat
1 70 9.9999885559 47.9998703003 19.9999980927 1 0 0 0 1 0 0 0 1 3004.dat
0 STEP
1 16 0 -72 0 1 0 0 0 1 0 0 0 1 pyramid2_rev.lxf_3_1_1
0 STEP
0 NOFILE 
0 FILE pyramid2_rev.lxf_3
0 Name: pyramid2_rev.lxf_3
0 Author: Undefined
1 14 30.0000019073 -24 10 1 0 0 0 1 0 0 0 1 3001.dat
1 14 49.9999847412 -24.0000286102 -49.9999923706 0 0 1 0 1 0 -1 0 0 3001.dat
1 14 -50 -23.9999523163 10 1 0 0 0 1 0 0 0 1 3001.dat
1 14 -50 -24.0000534058 -110 1 0 0 0 1 0 0 0 1 3001.dat
1 14 -70 -24.0000534058 -50.0000190735 0 0 1 0 1 0 -1 0 0 3001.dat
1 14 29.9999599457 -24.0000286102 -109.9999923706 1 0 0 0 1 0 0 0 1 3001.dat
0 STEP
1 16 -19.99999809 -72 19.99999809 1 0 0 0 1 0 0 0 1 pyramid2_rev.lxf_3_1
0 STEP
0 NOFILE 
0 FILE pyramid2_rev.lxf_5
0 Name: pyramid2_rev.lxf_5
0 Author: Undefined
1 2 30.0000019073 -24 10 1 0 0 0 1 0 0 0 1 3001.dat
1 2 29.9999885559 -24 -29.9999923706 1 0 0 0 1 0 0 0 1 3001.dat
1 2 29.9999923706 -48 -9.9999990463 1 0 0 0 1 0 0 0 1 3003.dat
0 STEP
0 NOFILE 
```

**Comment by mfeldt** [comment]
In the meantime, I found that the similar bugs ("firstSubModel is null" in this case) happen also with the cement truck as downloaded from brickhub.org.  Maybe there's some kind of trick I'm missing?

**Comment by LasseD** [comment]
Hi mfeld,

Have you tried to perform a forced reload of all resources of the web page?
The interface for MeshCollector was recently changed in order to accommodate transparency correctly.

When I try with your sample model, as well as the cement truck, I get to errors:

![image](https://user-images.githubusercontent.com/3670434/74436246-623cbd80-4e66-11ea-9463-c01de9c8201d.png)

**Comment by LasseD** [comment]
If reloading does not work, it might help to see what the code interprets. Please dump the content from running the following command in the console:

manager.ldrLoader.toLDR();

Then we can see if the first step is indeed empty when you run it. For me the content is:

`0 FILE pyramid2_rev.lxf
0 Name: pyramid2_rev.lxf

1 16 7.405297 -71.999832 219.851761 1 0 0 0 1 0 0 0 1 pyramid2_rev.lxf_0
0 STEP
1 4 79.999992 0.000072 -80 1 0 0 0 1 0 0 0 1 3001.dat
1 4 -0.000004 0.000072 -80 1 0 0 0 1 0 0 0 1 3001.dat
1 4 -80.000015 0.000072 -80 1 0 0 0 1 0 0 0 1 3001.dat
1 4 -100 0.000072 -20 0 0 -1 0 1 0 1 0 0 3001.dat
1 4 100 0.000097 -20 0 0 -1 0 1 0 1 0 0 3001.dat
1 4 -100.000031 0.00012 60 0 0 -1 0 1 0 1 0 0 3001.dat
1 4 100 0.00012 60 0 0 -1 0 1 0 1 0 0 3001.dat
1 4 80 0.00012 120.000015 -1 0 0 0 1 0 0 0 -1 3001.dat
1 4 0 0.000168 120.000015 -1 0 0 0 1 0 0 0 -1 3001.dat
1 4 -80.000015 0.000145 120.000031 -1 0 0 0 1 0 0 0 -1 3001.dat
0 STEP
1 1 59.999985 -24 -59.999992 1 0 0 0 1 0 0 0 1 3001.dat
1 1 -20.00001 -24 -59.999992 1 0 0 0 1 0 0 0 1 3001.dat
1 1 -79.999992 -24 -39.999992 0 0 -1 0 1 0 1 0 0 3001.dat
1 1 -79.999992 -24 40.000023 0 0 -1 0 1 0 1 0 0 3001.dat
1 1 -59.999992 -24 100.000023 1 0 0 0 1 0 0 0 1 3001.dat
1 1 19.999998 -24 100.000008 1 0 0 0 1 0 0 0 1 3001.dat
1 1 80 -24 80.000008 0 0 1 0 1 0 -1 0 0 3001.dat
1 1 79.999992 -24 0.000008 0 0 1 0 1 0 -1 0 0 3001.dat
0 STEP
1 16 10.000009 -23.999872 70.000008 1 0 0 0 1 0 0 0 1 pyramid2_rev.lxf_3
0 STEP
1 15 -19.999987 -71.99987 60.000008 1 0 0 0 1 0 0 0 1 3001.dat
1 15 19.999973 -71.999893 -19.999977 1 0 0 0 1 0 0 0 1 3001.dat
1 15 -40.000008 -71.999916 -0.000004 0 0 -1 0 1 0 1 0 0 3001.dat
1 15 39.999989 -71.999893 40.000015 0 0 -1 0 1 0 1 0 0 3001.dat
0 STEP
1 16 -30.000008 -71.999893 30.000025 1 0 0 0 1 0 0 0 1 pyramid2_rev.lxf_5

0 FILE pyramid2_rev.lxf_0
0 Name: pyramid2_rev.lxf_0

1 2 -17.40527 -24 -9.85173 -0.870263 0 0.492587 0 1 0 -0.492587 0 -0.870263 3622.dat
1 15 -17.405306 0.000001 -9.851776 -0.918277 0 -0.395938 0 1 0 0.395938 0 -0.918277 3622.dat
1 14 -17.405313 24 -9.851744 -0.229424 0 -0.973327 0 1 0 0.973327 0 -0.229424 3622.dat
1 1 -17.405302 47.999828 -9.85172 0.629037 0 -0.777376 0 1 0 0.777376 0 0.629037 3622.dat
1 4 -17.405304 72 -9.851757 0.99928 0 0.037947 0 1 0 -0.037947 0 0.99928 3622.dat

0 FILE pyramid2_rev.lxf_3
0 Name: pyramid2_rev.lxf_3

1 14 30.000002 -24 10 1 0 0 0 1 0 0 0 1 3001.dat
1 14 49.999985 -24.000029 -49.999992 0 0 1 0 1 0 -1 0 0 3001.dat
1 14 -50 -23.999952 10 1 0 0 0 1 0 0 0 1 3001.dat
1 14 -50 -24.000053 -110 1 0 0 0 1 0 0 0 1 3001.dat
1 14 -70 -24.000053 -50.000019 0 0 1 0 1 0 -1 0 0 3001.dat
1 14 29.99996 -24.000029 -109.999992 1 0 0 0 1 0 0 0 1 3001.dat
0 STEP
1 16 -19.999998 -72 19.999998 1 0 0 0 1 0 0 0 1 pyramid2_rev.lxf_3_1

0 FILE pyramid2_rev.lxf_3_1
0 Name: pyramid2_rev.lxf_3_1

1 70 10 -24 10 1 0 0 0 1 0 0 0 1 3003.dat
1 70 10 0.000001 10 1 0 0 0 1 0 0 0 1 3003.dat
1 70 10 24.000002 10 1 0 0 0 1 0 0 0 1 3003.dat
1 70 9.999989 47.99987 19.999998 1 0 0 0 1 0 0 0 1 3004.dat
0 STEP
1 16 0 -72 0 1 0 0 0 1 0 0 0 1 pyramid2_rev.lxf_3_1_1

0 FILE pyramid2_rev.lxf_3_1_1
0 Name: pyramid2_rev.lxf_3_1_1

1 70 10 -24 10 1 0 0 0 1 0 0 0 1 3003.dat
1 70 9.999996 0.000001 -10.000005 1 0 0 0 1 0 0 0 1 3001.dat
1 70 9.999996 0.000001 30.00001 1 0 0 0 1 0 0 0 1 3001.dat
1 70 10 24.000002 10 1 0 0 0 1 0 0 0 1 3003.dat

0 FILE pyramid2_rev.lxf_5
0 Name: pyramid2_rev.lxf_5

1 2 30.000002 -24 10 1 0 0 0 1 0 0 0 1 3001.dat
1 2 29.999989 -24 -29.999992 1 0 0 0 1 0 0 0 1 3001.dat
1 2 29.999992 -48 -9.999999 1 0 0 0 1 0 0 0 1 3003.dat
`

**Comment by mfeldt** [comment]
Well, maybe I did not.

In the meantime, I cloned a fresh copy, fired up a local http server, and apparently it works like a charm now.  So chances are, I messed something up.  Better close the issue!

  Cheers+thanks
  mark
