### ISSUE TITLE
Highlight new parts with colored boundaries similarly to how LEGO does in their instructions

### ISSUE THREAD

**Issue by LasseD** [LasseD/buildinginstructions.js#33]
This can be done by splitting rendering into 3 parts:

1) Draw parts from previous step (old part - the ones that can currently be drawn in a single color)
2) Draw new parts in a single highlighting color and have their size increased by x amount
3) Draw new parts with their correct colors and no size increase.

If you have a better (faster) way of achieving this, then please feel free to comment and make a pull request.

**Comment by urllib2** [comment]
Very interesting feature! 
If I want to change the color of the boundary what should I do please?

**Comment by urllib2** [comment]
Fantastic! 
Bunch of thanks

**Comment by LasseD** [comment]
Any time :)
