### ISSUE TITLE
Display the size of axle

### ISSUE THREAD

**Issue by urllib2** [LasseD/buildinginstructions.js#35]
Hi,
Is it possible to display the size of the axle in the parts panel?
Thanks

**Comment by LasseD** [comment]
Hi urllib2,

Do you mean something other than what you currently see in the sample files sample_instructions.htm and sample_partslist.htm where pli.js is used to show exactly this?

**Comment by urllib2** [comment]
I mean when I follow the building instructions in the sample_instructions.htm, in the parts panel how many modules does the axis have. In this picture, for example, a beginner can't predict the size of the axle.
![fig1](https://user-images.githubusercontent.com/46229376/84246965-4b019a00-aaff-11ea-9923-2a89af6cde0f.jpg)

**Comment by LasseD** [comment]
That is done using annotations from pli.js. So the answer to your original question is: Yes.

I have merged in the latest version from BrickHub.org to provide a more complete set of annotations

**Comment by urllib2** [comment]
Outstanding! I pulled the code and it works like a charm. But I didn't figure out how to change the shape and the color of circle.
![axle](https://user-images.githubusercontent.com/46229376/86509790-ca2a7b00-bdea-11ea-919d-3022d8946aad.png)

**Comment by LasseD** [comment]
That's written by 

context.arc(x+w*0.45, y+h*0.5, w*0.7, 0, 2*Math.PI, false);

in LDRPLIBuilder.js.

I agree that it is too big in your screenshot. The size was chosen based on the text size. It should be adjusted.

**Comment by LasseD** [comment]
Size of circles fixed in latest push to master branch.
