### ISSUE TITLE
Large parts in the parts panel

### ISSUE THREAD

**Issue by urllib2** [LasseD/buildinginstructions.js#36]
Hi, how could I reduce the size of the parts in the parts panel?
Thanks

**Comment by LasseD** [comment]
Hi urllib2,
Do you mean relative size of some large parts, such as base plates? (which can be done in pli.js)
or the complete PLI, which is done by dragging the PLI window to the desired size?
or the default size which is done by setting the options pliMaxWidthPercentage and pliMaxHeightPercentage as shown and documented in sample_instructions.htm?

Best regards
/ Lasse

**Comment by urllib2** [comment]
Hi Lasse,
I mean, in the parts panel there are some big parts. I want to know if there is a way that let me reduce their size so it becomes more realistic.
![fig2](https://user-images.githubusercontent.com/46229376/84247358-e561dd80-aaff-11ea-912e-1ad6035adf06.jpg)

**Comment by LasseD** [comment]
Right now the size is maximized in the PLI's (Parts list images) for the allowed size of the white box. The allowed size of the box is determined by the user dragging the handle, and in code by setting pliMaxWidthPercentage and pliMaxHeightPercentage.

If there is another restriction to the size of PLI's which you would like to see implemented, then please state how you would like to see the restriction on the size.

**Comment by urllib2** [comment]
And in which file could I find the pliMaxWidthPercentage and pliMaxHeightPercentage settings?

**Comment by LasseD** [comment]
Hi urllib2,
It is documented in sample_instructions.htm lines 131 and 132.

Best regards
/ Lasse
