### ISSUE TITLE
LDR.Studs.makeGenerators throwing a 3-4disc.dat not found error

### ISSUE THREAD

**Issue by billthefish** [LasseD/buildinginstructions.js#38]
**Describe the bug**
When LDR.Studs.makeGenerators is called a 3-4disc.dat error is received regardless of settings

**To Reproduce**
- load a model using LDR.Studs.makeGenerators('', 0, 0);
- "uncaught exception: Part not loaded: 3-4disc.dat" is recieved and model is not rendered
- if LDR.Studs.makeGenerators is commented out, scene renders fine

**Expected behavior**
3-4disc.dat to be loaded via the normal method (idToUrl)

**Screenshots**

**Device (please complete the following information):**
Windows, Firefox, 77.0.1

**Additional context**
I noted that 3-4disc.dat is commented out in LDRGenerator which may be the source of the issue. Regardless, this part should be attempted to be loaded via the normal method if not found.

**Comment by LasseD** [comment]
Thanks for the report. I can see that the line in the code says:

//'3-4disc.dat': () => LDR.Generator.makeDisc(3), // TODO Check that this is correct!

So I will verify that the generated output is correct.

**Comment by LasseD** [comment]
I have verified the output and pushed the uncommented line to the latest version of master.
