### ISSUE TITLE
LDR.OMR.ColorPartsAccordingToYear has wrong year

### ISSUE THREAD

**Issue by billthefish** [LasseD/buildinginstructions.js#42]
**Describe the bug**
LDR.OMR.ColorPartsAccordingToYear lists 2007 as the year of the change for Light/Dark Grey and Brown. The actual change was for year 2004 sets (that released to stores in late 2003).

**Comment by LasseD** [comment]
I can't believe that I got that one wrong. Thanks. It is fixed in the latest push to master.
