### ISSUE TITLE
Can't replace the background

### ISSUE THREAD

**Issue by urllib2** [LasseD/buildinginstructions.js#43]
Hello, 
I want to change the yellow background used in the submodels and make it white. How to proceed, please?
![yellow2](https://user-images.githubusercontent.com/46229376/94994948-c990b480-0592-11eb-92c7-d364883b66f0.png)

**Comment by LasseD** [comment]
Hi urllib,

The colors are defined in the following line of LDRStepHandler.js:

LDR.BackgroundColors = Array("FFFFFF", "FFFF88", "CCFFCC", "FFBB99", "99AAFF", "FF99FF", "D9FF99", "FFC299");

And for more advanced handling of background colors, the following method can be overwritten:

LDR.StepHandler.prototype.getBackgroundColorOfCurrentStep = function() {
    let level = this.getLevelOfCurrentStep();
    return LDR.BackgroundColors[level%LDR.BackgroundColors.length];
}

Best regards
/ Lasse

**Comment by urllib2** [comment]
Great!
