### ISSUE TITLE
Feature cleanUpPrimitivesAndSubParts has trouble with part 2444

### ISSUE THREAD

**Issue by mfeldt** [LasseD/buildinginstructions.js#45]
**Describe the bug**
When cleanUpPrimitivesAndSubParts is set to true when creating the InstructionsManager, and the model contains the part 2444.dat, all steps where the part is present in the PLI do not get rendered at all.  In addition, behaviour beyond the fist step containing the part gets sluggish and sometimes hard to predict. Jumping to a particular step by typing the number in the box does not work any more.

**To Reproduce**

1. Make a model containing 2444.dat e.g. in the fourth step
2. Step through instructions

**Expected behavior**
Normal behaviour

**Device (please complete the following information):**
 Windows 10, Android 10
  firefox, chrome, android webview

**Additional context**
It helps to simply set the option to false.

**Comment by LasseD** [comment]
I have added a test model (models/test_issue_45.ldr) where the issue does not appear. Can you please check and see if the issue persists?

**Comment by LasseD** [comment]
With the fix for issue #48 , this issue has been fixed as well.
