### ISSUE TITLE
Colors when LDConfig is updated.

### ISSUE THREAD

**Issue by billthefish** [LasseD/buildinginstructions.js#50]
LDConfig.ldr was updated in the 2022-01 release. The colors file needs to be updated. The ability to have the code parse the actual LDconfig to generate colors would also avoid this problem and be helpful.

**Comment by LasseD** [comment]
colors.js has been updated per the latest LDraw 2022_01 update.

I will keep this issue open until there is an app for creating the colors.js file without having to use a database.

**Comment by LasseD** [comment]
The tool for creating colors.js has been created: https://github.com/LasseD/buildinginstructions.js/blob/master/apps/color_converter.htm

Please note. The DB on brickhub.org merges Bricklink names and ID's into the colors.js file. ldconfig.ldr does not have this information, so it will be missing when using the color converter.

**Comment by billthefish** [comment]
While I can probably write my own thing, would it possible to have this as part of the software itself and just have a routine to parse the LDConfig if the file is supplied.

**Comment by LasseD** [comment]
That's a good idea. I have added this as an optional way of loading colors in the latest commit to master.

See sample_part_standard.htm for how to load colors using ldconfig.ldr

The new javascript file ldconfig.js is used for this, and an alternate path to ldconfig.ldr can be supplied in the call to load colors.
