### ISSUE TITLE
Make "invisible" geometry visible

### ISSUE THREAD

**Issue by billthefish** [LasseD/buildinginstructions.js#53]
There's some debate going on in the parts author community regarding the "invisible" primitives 1-16chrd and the associated ering primitives. Would it be possible to add functionality or a tutorial on how to enable these primitives to be viewed or highlighted in a model. Something like all the other faces grey but these prims in red or similar.

**Comment by LasseD** [comment]
I currently have this functionality by hiding all other primitives, but it appears to not work correctly. Here is how it should work. Go to a part that uses 1-16chrd, like https://brickhub.org/p/part.php?id=4-4ering&force=48 (with high res primitive forced) and click "Load full structure". Clicking on a line with the primitive below highlights the primitive and all of its points with the colors and size as specified in the settings below.

However... I have to fix this, as currently it doesn't seem to work.

**Comment by LasseD** [comment]
I have updated the file sample_part.htm on master to show dots where the empty files are. This has been done by adding a parse where empty part types get a point at their origin (a line with both points at 0,0,0). 

The error with primitive substitution on BrickHub has also been fixed.
