### ISSUE TITLE
setStuds requires files not referenced by the model being loaded.

### ISSUE THREAD

**Issue by billthefish** [LasseD/buildinginstructions.js#55]
**Describe the bug**
Some part fail to load with setStuds on unless specific files are loaded with the model

**To Reproduce**
LDraw.org uses a custom fetcher to prefetch all the LDraw files needed for a model and loads them into buildinginstructions.js. The parts/primitives are stored in an array and used by idToUrl like so (part_paths is an array of the part files):
```
var idToUrl = function(id) {
  if (part_paths[id]) {
    return [part_paths[id]];
  }
}
```
If setStuds is on, buildinginstructions.js will fail on loading unless the following files are also loaded with the model (note this list was determined experimentally so may not be all inclusive):
```
   "4-4edge.dat",
    "4-4ring2.dat",
    "1-4ring2.dat",
    "4-4ring5.dat",
    "4-4ring6.dat",
    "4-4disc.dat",
    "t01o0714.dat",
    "4-4cyli.dat",
    "4-4cyli2.dat",
    "logo.dat",
    "logo2.dat",
    "logo3.dat",
    "logo4.dat",
    "logo5.dat"
```
The only files on this list that would I expect to have to prefetch in regardless of the model contents would be the logo*.dat files. Any part files needed by the studs in the model being loaded are fetched with the rest of the parts/primitives in the the model.

**Expected behavior**
buildinginstructions.js should only need the files for the studs referenced in the actual model being loaded (plus the logo*.dat file for the reason I mentioned above)

**Comment by LasseD** [comment]
You are correct. This is poorly documented (as in... not documented). Generators can be used to create all but the "t01o0714.dat" part. I want to make the file fetching mechanism more reliable, which should help with issues like this.

**Comment by LasseD** [comment]
In the latest push to master I have rewritten LDRGenerator.js and LDStuds.js so that part types are constructed on the fly.
Are you observing the problem when including both of these files?

**Comment by billthefish** [comment]
I just pulled from master, Initial testing suggest this problem is fixed.
